Currently not relevant: Use service.yaml



apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: blog-services
  namespace: default # The namespace the app will use
  labels:
    app: blog-services
spec:
  address:
    hostname: blog-services.default.svc.cluster.local
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dswoboda/blog-services:v0.1
            imagePullPolicy: IfNotPresent
          ports:
            - name: http
              port: 80